version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file:
      - .env.example
    environment:
      - ENVIRONMENT=docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    env_file:
      - .env.example
    environment:
      - ENVIRONMENT=docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A src.workers.knowledge_worker worker --loglevel=info

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: sales_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  vectordb-migrate:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    command: alembic upgrade head
    env_file:
      - .env.example
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - migrate

volumes:
  postgres-data:
