line-length = 100
exclude = [
  "build",
  "dist",
  "venv",
  "scripts",
  "docs"
]
select = ["E", "F", "I", "UP", "B", "S", "W", "PL", "RUF"]
ignore = ["S101"]

[per-file-ignores]
"tests/**" = ["S101", "D100", "D103"]
